In [14]:
import numpy as np

In [15]:
# Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz en la que cada elemento es una suma de elementos de las 2 matrices? (solo puede usar numpy como librería, si realiza la matriz con otro paquete el ejercicio no es válido)

var_rows = 4
var_cols = 4

var_random_matrix_1 = np.random.randint (0, 1000, size = (var_rows, var_cols))
var_random_matrix_2 = np.random.randint (0, 1000, size = (var_rows, var_cols))

var_summed_matrix = np.add (var_random_matrix_1, var_random_matrix_2)

print (var_random_matrix_1)
print (var_random_matrix_2)
print (var_summed_matrix)

[[129 914 400 266]
 [140 877 367 484]
 [932  68 582 524]
 [885  20  43 779]]
[[414 249 368 634]
 [770 659 368 516]
 [940 635 990 770]
 [ 71 108 764 287]]
[[ 543 1163  768  900]
 [ 910 1536  735 1000]
 [1872  703 1572 1294]
 [ 956  128  807 1066]]


In [16]:
# Cree una matriz de identidad de dimensión 4

var_rows = 4

var_identity_matrix = np.eye (var_rows)

print (var_identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una matriz numpy booleana

var_rows = 4
var_cols = 4

var_random_matrix = np.random.randint (0, 2, size = (var_rows, var_cols))

print (var_random_matrix)

var_random_matrix = np.asarray (var_random_matrix, dtype = bool)

print (var_random_matrix)

[[1 0 0 1]
 [0 1 0 0]
 [1 0 1 1]
 [0 0 0 1]]
[[ True False False  True]
 [False  True False False]
 [ True False  True  True]
 [False False False  True]]


In [18]:
# Genere una secuencia de números en forma de matriz numpy de 0 a 100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...

var_rows = 3
var_cols = 5

var_sequence = np.arange (0, 1000, 2)

print (var_sequence)

var_sequence = var_sequence[:(var_rows * var_cols)]

print (var_sequence)

var_sequence = var_sequence.reshape (var_rows, var_cols)

print (var_sequence)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49